
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qujkafezsjwijeemyhdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1amthZmV6c2p3aWplZW15aGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTQwNTQsImV4cCI6MjA2MTU3MDA1NH0.idPksE8FMvinPkyoBYdHcFWSzKJQY68YJbtA4hs506E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true
    }
  }
);
